language: node_js

node_js:
   - node

script:
  - echo "Deploying!"

install:
   - npm install -g --silent firebase-tools # installs firebase to run firebase deploy
   - npm install -g --silent @angular/cli

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive # firebase deploy after angular-cli build

notifications:
  email:
    on_failure: change
    on_success: change 